### ISSUE TITLE
Remove hardcoded configuration

### ISSUE THREAD

**Issue by dxjohnson-godaddy** [jstack-godaddy/cluster-api#1]
The following I believe should be in a configuration json file maybe that is read in at program start. This way, we do not need to do a new release as we add things.
https://github.com/jstack-godaddy/cluster-api/blob/6479b3d1d2a9003fb895029919642bece00c13d3/v1/helpers/ngosClient.go#L20-L55

**Comment by jstack-godaddy** [comment]
done
