### ISSUE TITLE
Check connection before creating server

### ISSUE THREAD

**Issue by dxjohnson-godaddy** [jstack-godaddy/cluster-api#4]
We should be doing the ping() before we are creating servers in openstack. If we do not, we could end up with servers which exist in OS:NG but not in our metadata.
https://github.com/jstack-godaddy/cluster-api/blob/335fb8d0daf11c5901bdade7d536ec49cc53f36c/v1/endpoints/cluster_endpoint/create.go#L62-L66

**Comment by jstack-godaddy** [comment]
done
